-- ════════════════════════════════════════════════════════════════════
-- Etiket Studio · 0001 — Doğtaş katalog şeması
--
-- KAYNAK: D:\GoogleDrive\Fiyat\etiket-web\app\models\* (SQLAlchemy modelleri)
-- HEDEF:  Supabase Postgres (public schema)
--
-- Çalıştırma:
--   1) Supabase Dashboard → SQL Editor → New query
--   2) Bu dosyayı yapıştır → "Run"
--
-- Idempotent: tekrar tekrar çalıştırılabilir, hata vermez (CREATE IF NOT EXISTS).
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
-- 1) TABLOLAR
-- ════════════════════════════════════════════════════════════════════

-- ─── kategoriler ────────────────────────────────────────────────────
create table if not exists public.kategoriler (
  id                integer primary key generated by default as identity,
  ad                varchar(120) not null unique,
  sira              integer      not null default 0,
  olusturma_tarihi  timestamptz  not null default now()
);


-- ─── koleksiyonlar (kategori → 1..N koleksiyon) ─────────────────────
create table if not exists public.koleksiyonlar (
  id                integer primary key generated by default as identity,
  kategori_id       integer not null references public.kategoriler(id) on delete cascade,
  ad                varchar(200) not null,
  olusturma_tarihi  timestamptz  not null default now(),
  constraint uq_koleksiyon_kategori_ad unique (kategori_id, ad)
);
create index if not exists ix_koleksiyonlar_kategori_id
  on public.koleksiyonlar(kategori_id);


-- ─── urunler (SKU bazlı, denormalize son fiyatlar) ──────────────────
-- NOT: Fiyatlar TL cinsinden tam sayı (integer). Kuruş kullanılmıyor.
create table if not exists public.urunler (
  id                   integer primary key generated by default as identity,
  sku                  varchar(50)  not null unique,
  urun_adi_tam         varchar(300) not null,
  url                  varchar(500),
  son_liste_fiyat      integer,
  son_perakende_fiyat  integer,
  olusturma_tarihi     timestamptz  not null default now()
);
create index if not exists ix_urunler_sku on public.urunler(sku);


-- ─── fiyatlar (her scrape için verification kaydı = fiyat tarihçesi) ─
create table if not exists public.fiyatlar (
  id               integer primary key generated by default as identity,
  urun_id          integer not null references public.urunler(id) on delete cascade,
  liste_fiyat      integer,
  perakende_fiyat  integer,
  kaynak           varchar(30)  not null default 'manual',  -- manual | dogtas_com | sheets | import
  kayit_tarihi     timestamptz  not null default now()
);
create index if not exists ix_fiyatlar_urun_id      on public.fiyatlar(urun_id);
create index if not exists ix_fiyatlar_kayit_tarihi on public.fiyatlar(kayit_tarihi);


-- ─── urun ↔ koleksiyon (M2M ara tablosu) ────────────────────────────
-- Bir SKU birden fazla koleksiyonda olabilir (örn. aynı puf hem COSTA hem TOSCANA'da).
create table if not exists public.urun_koleksiyon (
  urun_id        integer not null references public.urunler(id) on delete cascade,
  koleksiyon_id  integer not null references public.koleksiyonlar(id) on delete cascade,
  primary key (urun_id, koleksiyon_id)
);


-- ─── kategori_kurallari (scraper iş kuralları) ──────────────────────
-- tur='filtre'      → eşleşen ürünleri DB'ye yazma
-- tur='duplikasyon' → ürünü hedef_kategori altında da koleksiyona bağla
create table if not exists public.kategori_kurallari (
  id                integer primary key generated by default as identity,
  tur               varchar(20)  not null,
  kaynak_kategori   varchar(120),
  hedef_kategori    varchar(120),
  kelimeler         varchar(500),
  aktif             boolean      not null default true,
  olusturma_tarihi  timestamptz  not null default now()
);
create index if not exists ix_kategori_kurallari_tur on public.kategori_kurallari(tur);


-- ════════════════════════════════════════════════════════════════════
-- 2) ROW LEVEL SECURITY
-- ════════════════════════════════════════════════════════════════════
-- Mantık:
--   - Scraper:  direct Postgres connection ('postgres' superuser) ile yazar
--               → RLS bypass. Hiçbir politika onu engellemez.
--   - Django:   supabase-py (anon key + JWT) ile bağlanır
--               → 'authenticated' rolü ile sadece SELECT yapabilir.
--   - Anonim:   politika yok → 0 satır görür.

alter table public.kategoriler        enable row level security;
alter table public.koleksiyonlar      enable row level security;
alter table public.urunler            enable row level security;
alter table public.fiyatlar           enable row level security;
alter table public.urun_koleksiyon    enable row level security;
alter table public.kategori_kurallari enable row level security;

-- Authenticated → SELECT (read-only) ────────────────────────────────

drop policy if exists "auth_select" on public.kategoriler;
create policy "auth_select" on public.kategoriler
  for select to authenticated using (true);

drop policy if exists "auth_select" on public.koleksiyonlar;
create policy "auth_select" on public.koleksiyonlar
  for select to authenticated using (true);

drop policy if exists "auth_select" on public.urunler;
create policy "auth_select" on public.urunler
  for select to authenticated using (true);

drop policy if exists "auth_select" on public.fiyatlar;
create policy "auth_select" on public.fiyatlar
  for select to authenticated using (true);

drop policy if exists "auth_select" on public.urun_koleksiyon;
create policy "auth_select" on public.urun_koleksiyon
  for select to authenticated using (true);

drop policy if exists "auth_select" on public.kategori_kurallari;
create policy "auth_select" on public.kategori_kurallari
  for select to authenticated using (true);


-- ════════════════════════════════════════════════════════════════════
-- 3) İSTATİSTİK / DOĞRULAMA
-- ════════════════════════════════════════════════════════════════════
-- Çalıştırdıktan sonra şunlarla kontrol edebilirsin:

-- Tablolar:
--   select tablename from pg_tables where schemaname='public' order by tablename;

-- Politikalar:
--   select schemaname, tablename, policyname, roles, cmd
--   from pg_policies where schemaname='public' order by tablename;

-- Sayıları:
--   select 'kategoriler'        as tablo, count(*) from public.kategoriler
--   union all select 'koleksiyonlar',      count(*) from public.koleksiyonlar
--   union all select 'urunler',            count(*) from public.urunler
--   union all select 'fiyatlar',           count(*) from public.fiyatlar
--   union all select 'urun_koleksiyon',    count(*) from public.urun_koleksiyon
--   union all select 'kategori_kurallari', count(*) from public.kategori_kurallari;
