-- ════════════════════════════════════════════════════════════════════
-- 0004 — Kombinasyon (TakimKombinasyonu eski projeden port)
--
-- Idempotent: tekrar tekrar çalıştırılabilir.
-- Inline constraint yerine CREATE UNIQUE INDEX IF NOT EXISTS kullanılıyor
-- (re-run'da çakışma yok).
-- ════════════════════════════════════════════════════════════════════


-- ─── kombinasyonlar ────────────────────────────────────────────────
create table if not exists public.kombinasyonlar (
  id                integer primary key generated by default as identity,
  koleksiyon_id     integer not null references public.koleksiyonlar(id) on delete cascade,
  ad                varchar(200) not null,
  sira              integer not null default 0,
  olusturma_tarihi  timestamptz not null default now()
);
create unique index if not exists uq_kombinasyon_kol_ad
  on public.kombinasyonlar (koleksiyon_id, ad);
create index if not exists ix_kombinasyonlar_koleksiyon_id
  on public.kombinasyonlar(koleksiyon_id);


-- ─── kombinasyon_urunleri (M2M with miktar) ────────────────────────
create table if not exists public.kombinasyon_urunleri (
  id              integer primary key generated by default as identity,
  kombinasyon_id  integer not null references public.kombinasyonlar(id) on delete cascade,
  urun_id         integer not null references public.urunler(id) on delete restrict,
  miktar          integer not null default 1
);

-- CHECK constraint (idempotent)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'ck_kombinasyon_urun_miktar'
  ) then
    alter table public.kombinasyon_urunleri
      add constraint ck_kombinasyon_urun_miktar check (miktar >= 1);
  end if;
end $$;

create unique index if not exists uq_kombinasyon_urun
  on public.kombinasyon_urunleri (kombinasyon_id, urun_id);
create index if not exists ix_kombinasyon_urunleri_kombinasyon
  on public.kombinasyon_urunleri(kombinasyon_id);
create index if not exists ix_kombinasyon_urunleri_urun
  on public.kombinasyon_urunleri(urun_id);


-- ─── kategori_kombinasyon_kurallari (regex tabanlı oto-bul) ────────
create table if not exists public.kategori_kombinasyon_kurallari (
  id                integer primary key generated by default as identity,
  kategori_id       integer not null references public.kategoriler(id) on delete cascade,
  kombinasyon_adi   varchar(200) not null,
  patterns          jsonb not null,
  adet_overrides    jsonb not null default '{}'::jsonb,
  sira              integer not null default 0,
  aktif             boolean not null default true,
  olusturma_tarihi  timestamptz not null default now()
);
create unique index if not exists uq_kkk_kategori_ad
  on public.kategori_kombinasyon_kurallari (kategori_id, kombinasyon_adi);
create index if not exists ix_kkk_kategori
  on public.kategori_kombinasyon_kurallari(kategori_id);


-- ─── RLS ───────────────────────────────────────────────────────────
alter table public.kombinasyonlar                  enable row level security;
alter table public.kombinasyon_urunleri            enable row level security;
alter table public.kategori_kombinasyon_kurallari  enable row level security;

drop policy if exists "auth_select" on public.kombinasyonlar;
create policy "auth_select" on public.kombinasyonlar
  for select to authenticated using (true);

drop policy if exists "auth_select" on public.kombinasyon_urunleri;
create policy "auth_select" on public.kombinasyon_urunleri
  for select to authenticated using (true);

drop policy if exists "auth_select" on public.kategori_kombinasyon_kurallari;
create policy "auth_select" on public.kategori_kombinasyon_kurallari
  for select to authenticated using (true);


-- ════════════════════════════════════════════════════════════════════
-- SEED — eski projedeki KOMBINASYON_KURALLARI (idempotent)
-- ════════════════════════════════════════════════════════════════════

-- Yatak Odası
do $$
declare kid integer;
begin
  select id into kid from public.kategoriler where ad = 'Yatak Odası';
  if kid is not null then
    insert into public.kategori_kombinasyon_kurallari (kategori_id, kombinasyon_adi, patterns, adet_overrides, sira)
    values
      (kid, '6 Kapaklı, Karyola',
       '["(?i)\\b6\\s*kapak(lı)?\\b",
         "(?i)(?=.*ba(ş|s)l(ı|i)k)(?=.*160)",
         "(?i)^(?!.*180)(?!.*Baza)(?!.*Başlıklı).*Karyola.*160.*$",
         "(?i)^(?!.*ayna)(?!.*ikili)(?!.*dar)(?!.*yüksek)(?=.*şifonyer).*$",
         "(?i)^(?=.*ayna)(?=.*(konsol|şifonyer)).*$",
         "(?i)(?=.*kom[oi]din)(?=.*(çift|çekmece))?"
        ]'::jsonb,
       '{"(?i)(?=.*kom[oi]din)(?=.*(çift|çekmece))?": 2}'::jsonb,
       1),
      (kid, '6 Kapaklı, Baza',
       '["(?i)\\b6\\s*kapak(lı)?\\b",
         "(?i)(?=.*ba(ş|s)l(ı|i)k)(?=.*160)",
         "(?i)^(?!.*başlıklı)(?=.*baza)(?=.*160).*$",
         "(?i)^(?!.*ayna)(?!.*ikili)(?!.*dar)(?!.*yüksek)(?=.*şifonyer).*$",
         "(?i)^(?=.*ayna)(?=.*(konsol|şifonyer)).*$",
         "(?i)(?=.*kom[oi]din)(?=.*(çift|çekmece))?"
        ]'::jsonb,
       '{"(?i)(?=.*kom[oi]din)(?=.*(çift|çekmece))?": 2}'::jsonb,
       2),
      (kid, '5 Kapaklı, Karyola',
       '["(?i)\\b5\\s*kapak(lı)?\\b",
         "(?i)(?=.*ba(ş|s)l(ı|i)k)(?=.*160)",
         "(?i)^(?!.*180)(?!.*Baza)(?!.*Başlıklı).*Karyola.*160.*$",
         "(?i)^(?!.*ayna)(?!.*ikili)(?!.*dar)(?!.*yüksek)(?=.*şifonyer).*$",
         "(?i)^(?=.*ayna)(?=.*(konsol|şifonyer)).*$",
         "(?i)(?=.*kom[oi]din)(?=.*(çift|çekmece))?"
        ]'::jsonb,
       '{"(?i)(?=.*kom[oi]din)(?=.*(çift|çekmece))?": 2}'::jsonb,
       3),
      (kid, '5 Kapaklı, Baza',
       '["(?i)\\b5\\s*kapak(lı)?\\b",
         "(?i)(?=.*ba(ş|s)l(ı|i)k)(?=.*160)",
         "(?i)^(?!.*başlıklı)(?=.*baza)(?=.*160).*$",
         "(?i)^(?!.*ayna)(?!.*ikili)(?!.*dar)(?!.*yüksek)(?=.*şifonyer).*$",
         "(?i)^(?=.*ayna)(?=.*(konsol|şifonyer)).*$",
         "(?i)(?=.*kom[oi]din)(?=.*(çift|çekmece))?"
        ]'::jsonb,
       '{"(?i)(?=.*kom[oi]din)(?=.*(çift|çekmece))?": 2}'::jsonb,
       4)
    on conflict (kategori_id, kombinasyon_adi) do nothing;
  end if;
end $$;

-- Yemek Odası
do $$
declare kid integer;
begin
  select id into kid from public.kategoriler where ad = 'Yemek Odası';
  if kid is not null then
    insert into public.kategori_kombinasyon_kurallari (kategori_id, kombinasyon_adi, patterns, adet_overrides, sira)
    values
      (kid, 'Konsol, Açılır, Sandalye*6',
       '["(?i)^(?!.*ayna)(?!.*mini)(?=.*konsol).*$",
         "(?i)^(?=.*ayna)(?=.*(konsol|şifonyer)).*$",
         "(?i)^(?!.*sabit)(?=.*yemek)(?=.*açılır).*$",
         "(?i)^(?!.*kol)(?=.*(sandalye|sand\\.)).*$"
        ]'::jsonb,
       '{"(?i)^(?!.*kol)(?=.*(sandalye|sand\\.)).*$": 6}'::jsonb,
       1),
      (kid, 'Konsol, Sabit, Sandalye*6',
       '["(?i)^(?!.*ayna)(?!.*mini)(?=.*konsol).*$",
         "(?i)^(?=.*ayna)(?=.*(konsol|şifonyer)).*$",
         "(?i)^(?!.*açılır)(?=.*yemek)(?=.*sabit).*$",
         "(?i)^(?!.*kol)(?=.*(sandalye|sand\\.)).*$"
        ]'::jsonb,
       '{"(?i)^(?!.*kol)(?=.*(sandalye|sand\\.)).*$": 6}'::jsonb,
       2),
      (kid, 'Açılır, Sandalye*6',
       '["(?i)^(?!.*sabit)(?=.*yemek)(?=.*açılır).*$",
         "(?i)^(?!.*kol)(?=.*(sandalye|sand\\.)).*$"
        ]'::jsonb,
       '{"(?i)^(?!.*kol)(?=.*(sandalye|sand\\.)).*$": 6}'::jsonb,
       3),
      (kid, 'Sabit, Sandalye*6',
       '["(?i)^(?!.*açılır)(?=.*yemek)(?=.*sabit).*$",
         "(?i)^(?!.*kol)(?=.*(sandalye|sand\\.)).*$"
        ]'::jsonb,
       '{"(?i)^(?!.*kol)(?=.*(sandalye|sand\\.)).*$": 6}'::jsonb,
       4)
    on conflict (kategori_id, kombinasyon_adi) do nothing;
  end if;
end $$;

-- Oturma Grubu
do $$
declare kid integer;
begin
  select id into kid from public.kategoriler where ad = 'Oturma Grubu';
  if kid is not null then
    insert into public.kategori_kombinasyon_kurallari (kategori_id, kombinasyon_adi, patterns, adet_overrides, sira)
    values
      (kid, 'Üçlü*2, Berjer*2',
       '["(?i)^(?=.*(berjer|tekli)).*$",
         "(?i)^(?=.*(üçlü)).*$"
        ]'::jsonb,
       '{"(?i)^(?=.*(berjer|tekli)).*$": 2,
         "(?i)^(?=.*(üçlü)).*$": 2}'::jsonb,
       1)
    on conflict (kategori_id, kombinasyon_adi) do nothing;
  end if;
end $$;

-- Doğtaş Genç ve Çocuk Odası
do $$
declare kid integer;
begin
  select id into kid from public.kategoriler where ad = 'Doğtaş Genç ve Çocuk Odası';
  if kid is not null then
    insert into public.kategori_kombinasyon_kurallari (kategori_id, kombinasyon_adi, patterns, adet_overrides, sira)
    values
      (kid, '3 Kapaklı, 100 Karyola, Çalışma Masası',
       '["(?i).*(3\\s*kapa|3\\s*kapı).*dolap.*",
         "(?i)^(?=.*(ba(ş|s)l(ı|i)k|100))(?!.*başlıksız)(?!.*karyola).*",
         "(?i)^(?=.*karyola)(?=.*100)(?!.*baza)(?=.*(başlıksız|kasa))?.*",
         "(?i)^(?=.*(çalışma|calısma))(?=.*masa)(?!.*üst)(?!.*modül)(?!.*eko)(?!.*kompakt).*"
        ]'::jsonb,
       '{}'::jsonb,
       1),
      (kid, '3 Kapaklı, 100 Baza, Çalışma Masası',
       '["(?i).*(3\\s*kapa|3\\s*kapı).*dolap.*",
         "(?i)^(?=.*(başlık|100))(?!.*başlıksız)(?!.*karyola).*",
         "(?i)^(?=.*baza)(?=.*100).*",
         "(?i)^(?=.*(çalışma|calısma))(?=.*masa)(?!.*üst)(?!.*modül)(?!.*eko)(?!.*kompakt).*"
        ]'::jsonb,
       '{}'::jsonb,
       2)
    on conflict (kategori_id, kombinasyon_adi) do nothing;
  end if;
end $$;
